### ISSUE TITLE
Delete photo does not work

### ISSUE THREAD

**Issue by nielsvanduinen** [stanaka/lightroom-google-photo-plugin#11]
Uploading (Publishing) works. Create an Album in LR works BUT you have to first create an album in GP with the same name to make it possible to publish, HOWEVER, delete a photo does not work. It deletes it from the LR album but leaves it on the GP album...

**Comment by tassu** [comment]
Same here but creating new album don`t publish (Same issue as the older ones) . Haven`t tried your solution with albums.

**Comment by stanaka** [comment]
Unfortunately Google stoped to support many features in Picasa Web Data API.
I'm going to migrate new Google Photos API. Please wait for a while, Google Photos API does not support deleting though...
https://github.com/stanaka/lightroom-google-photo-plugin/pull/15
