### ISSUE TITLE
Can't update this collection - 2000 Photo

### ISSUE THREAD

**Issue by realkibou** [stanaka/lightroom-google-photo-plugin#12]
Hello there,

I uploaded 2000x photos in batches of 468x photos. It returned an error after 468x, but I could just push 'Publish' again. However, now after exactly 2000x pictures it stop working.

I re-auth again, used a different album, waited 48h, but nothing helped. Any ideas?

EDIT: Apparently Google Photos still has an album limit size of 2000x Photos. Just deleted the album, moved the pictures back to the original publishing folder "Photos" and it worked. Case closed.

Best regards,
realKibou

**Comment by stanaka** [comment]
Thanks!
