### ISSUE TITLE
Unable to change upload preferences

### ISSUE THREAD

**Issue by ghost** [stanaka/lightroom-google-photo-plugin#14]
It would be great to change the upload preferences. Current and default way is "original quality" but not everyone prefers that. Would be great to have the "unlimited compressed backup" option. Thanks

**Comment by stanaka** [comment]
I'm going to migrate new Google Photos API as Picasa Web Data API is obsoleted. Unfortunately Google Photos API only supports "original quality" setting. Please wait for Google's providing another option.
> Note: All media items uploaded to Google Photos through the API are stored in full resolution at original quality. If your uploads exceed 25MB per user, your application should remind the user that these uploads will count towards storage in their Google Account.
https://developers.google.com/photos/library/guides/upload-media
