### ISSUE TITLE
ID Error (#402)

### ISSUE THREAD

**Issue by pieralessandro** [stanaka/lightroom-google-photo-plugin#21]
Dear Stanaka,
first of all thank for you plugin!
I'm trying to use the latest release of LGP (lightroom-google-photo-plugin) (downloaded from GitHub on 26/08/2018) on LR Classic 7.5, but I get an error on Google Authorization ID webpage.
The Error (n° 402) says that the ID is missing and I cannot find on the plugin setup page any field about my google ID.
What can i try to overcome this issue?
Best regards
Alessandro

**Comment by stanaka** [comment]
It works now. See #23
