### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by ericvrp** [stanaka/lightroom-google-photo-plugin#23]
After login in to my "Google Photo account" from the "Lightroom plugin manager" I get redirected to a page that says:

> Sign in with Google temporarily disabled for this app
>
> This app has not been verified yet by Google in order to use Google Sign In.

**Comment by stanaka** [comment]
I'm asking Google to verify this plugin. It takes for a while.

**Comment by corteszz** [comment]
Any updates?

**Comment by jaketame** [comment]
Getting this error too, unable to use my own API either, it redirects to an unknown page.

**Comment by dhrandy** [comment]
I really hope this gets fixed!!

**Comment by leemmcc** [comment]
Getting the same thing still.

**Comment by cmunk** [comment]
Any luck with this? Any work-around?

**Comment by aperrot42** [comment]
Same thing for me.

**Comment by aperrot42** [comment]
Even with own api key, lightroom does not let you save plugin settings until you were able to log to google account. And trying to log gives an invalid redirect.

**Comment by thesushiman** [comment]
Has this been certified yet?  I would really like this to work...

**Comment by martinparoll** [comment]
Awaiting as well

**Comment by cameronkruse** [comment]
The last stable release still works. I only got this error with the new beta versions.

**Comment by stanaka** [comment]
I've been asking Google to review a Google OAuth authentication token for this plugin. It just takes time.
Please be patient.

**Comment by metawise** [comment]
Still waiting for this. Hopefully, Google will verify and be able to log in.

**Comment by tamkaho** [comment]
I hope to be able to use the plugin too!

**Comment by leigsnering** [comment]
How does it go on here?

**Comment by Harald777** [comment]
Hope to see this solved soon, would love to use this plugin.

**Comment by corteszz** [comment]
This looks dead... Any one with another solution?

**Comment by cameronkruse** [comment]
So I think this issue is only related to the v0.2 alpha releases; can anyone confirm this?

The v0.1 worked fine for me and meets the core needs. https://github.com/stanaka/lightroom-google-photo-plugin/releases/tag/v0.1

**Comment by stanaka** [comment]
Finally Google has been approved the oauth token which this plugin uses!
Thank you for your patience.
