### ISSUE TITLE
Error: invalid_request

### ISSUE THREAD

**Issue by lanky8804** [stanaka/lightroom-google-photo-plugin#9]
When clicking login button via Publishing Manager get error 400 (OAuth2 Error) on web browser and get no verification token required by plugin. Anyone else getting this issue?

**Comment by brosapinto** [comment]
I'm also getting a `400` error, with the message `Missing required parameter: client_id`:

```
scope=https://picasaweb.google.com/data/
redirect_uri=https://stanaka.github.io/lightroom-google-photo-plugin/redirect
response_type=code
prompt=consent
access_type=offline
client_id=
```

**Comment by timodegen** [comment]
Same for me.

**Comment by stanaka** [comment]
Yes. Please download from the release.
Also I'm going to migrate new Google Photos API. Please wait for a while.
https://github.com/stanaka/lightroom-google-photo-plugin/pull/15
